name: 'Build and Run'

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - 'master'
    tags:
      - '*-echelon'

permissions:
  contents: read
  pull-requests: read

jobs:
  br1-allnoconfig:
    runs-on: "ubuntu-latest"
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v4
        with:
          fetch-depth: '3'
      # START: Workaround bug (Fetch Tags)
      #   Problem: actions/checkout@v4 with [fetch-tags: 'true'] fails when triggered by tag create/push event.
      #   Solution: Use a separate and subsequent tag fetch step
          #fetch-tags: 'true'
          fetch-tags: 'false'

      # Now we can fetch the tags
      - name: 'Fetch Tags'
        run: 'git fetch --tags'
      # END: Workaround bug (Fetch Tags)

      - name: 'Git Show'
        run: 'git show'

      - name: 'Update Runner'
        run: 'sudo .github/workflows/build_and_run/update.sh'

      - name: 'Install Dependencies'
        run: 'sudo .github/workflows/build_and_run/install_dep.sh'

      - name: 'Build 1'
        run: '.github/workflows/build_and_run/build_1.sh'

      - name: 'Run 1'
        run: '.github/workflows/build_and_run/run_1.sh'

  br2-defconfig:
    runs-on: "ubuntu-latest"
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v4
        with:
          fetch-depth: '3'
      # START: Workaround bug (Fetch Tags)
      #   Problem: actions/checkout@v4 with [fetch-tags: 'true'] fails when triggered by tag create/push event.
      #   Solution: Use a separate and subsequent tag fetch step
          #fetch-tags: 'true'
          fetch-tags: 'false'

      # Now we can fetch the tags
      - name: 'Fetch Tags'
        run: 'git fetch --tags'
      # END: Workaround bug (Fetch Tags)

      - name: 'Git Show'
        run: 'git show'

      - name: 'Update Runner'
        run: 'sudo .github/workflows/build_and_run/update.sh'

      - name: 'Install Dependencies'
        run: 'sudo .github/workflows/build_and_run/install_dep.sh'

      - name: 'Build 2'
        run: '.github/workflows/build_and_run/build_2.sh'

      - name: 'Run 2'
        run: '.github/workflows/build_and_run/run_2.sh'

  br3-allyesconfig:
    runs-on: "ubuntu-latest"
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v4
        with:
          fetch-depth: '3'
      # START: Workaround bug (Fetch Tags)
      #   Problem: actions/checkout@v4 with [fetch-tags: 'true'] fails when triggered by tag create/push event.
      #   Solution: Use a separate and subsequent tag fetch step
          #fetch-tags: 'true'
          fetch-tags: 'false'

      # Now we can fetch the tags
      - name: 'Fetch Tags'
        run: 'git fetch --tags'
      # END: Workaround bug (Fetch Tags)

      - name: 'Git Show'
        run: 'git show'

      - name: 'Update Runner'
        run: 'sudo .github/workflows/build_and_run/update.sh'

      - name: 'Install Dependencies'
        run: 'sudo .github/workflows/build_and_run/install_dep.sh'

      - name: 'Build 3'
        run: '.github/workflows/build_and_run/build_3.sh'

      - name: 'Run 3'
        run: '.github/workflows/build_and_run/run_3.sh'

  br4-rv32_defconfig:
    runs-on: "ubuntu-latest"
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v4
        with:
          fetch-depth: '3'
      # START: Workaround bug (Fetch Tags)
      #   Problem: actions/checkout@v4 with [fetch-tags: 'true'] fails when triggered by tag create/push event.
      #   Solution: Use a separate and subsequent tag fetch step
          #fetch-tags: 'true'
          fetch-tags: 'false'

      # Now we can fetch the tags
      - name: 'Fetch Tags'
        run: 'git fetch --tags'
      # END: Workaround bug (Fetch Tags)

      - name: 'Git Show'
        run: 'git show'

      - name: 'Checkout - Echelon SBI'
        uses: actions/checkout@v4
        with:
          repository: 'echelonxray/echelon_sbi'
          ref: 'ghactions_test_version'
          path: 'echelon_sbi'
          fetch-depth: '0'
          fetch-tags: 'true'

      - name: 'Update Runner'
        run: 'sudo .github/workflows/build_and_run/update.sh'

      - name: 'Install Dependencies'
        run: 'sudo .github/workflows/build_and_run/install_dep.sh'

      - name: 'Build 4'
        run: '.github/workflows/build_and_run/build_4.sh'

      - name: 'Run 4'
        run: '.github/workflows/build_and_run/run_4.sh'

  br5-Custom_Config:
    runs-on: "ubuntu-latest"
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v4
        with:
          fetch-depth: '3'
      # START: Workaround bug (Fetch Tags)
      #   Problem: actions/checkout@v4 with [fetch-tags: 'true'] fails when triggered by tag create/push event.
      #   Solution: Use a separate and subsequent tag fetch step
          #fetch-tags: 'true'
          fetch-tags: 'false'

      # Now we can fetch the tags
      - name: 'Fetch Tags'
        run: 'git fetch --tags'
      # END: Workaround bug (Fetch Tags)

      - name: 'Git Show'
        run: 'git show'

      - name: 'Checkout - Echelon Emulator (rv32iasu)'
        uses: actions/checkout@v4
        with:
          repository: 'echelonxray/rv32iasu_emulator'
          ref: 'ghactions_test_version'
          path: 'rv32iasu_emulator'
          fetch-depth: '0'
          fetch-tags: 'true'

      - name: 'Checkout - Echelon SBI'
        uses: actions/checkout@v4
        with:
          repository: 'echelonxray/echelon_sbi'
          ref: 'ghactions_test_version'
          path: 'echelon_sbi'
          fetch-depth: '0'
          fetch-tags: 'true'

      - name: 'Update Runner'
        run: 'sudo .github/workflows/build_and_run/update.sh'

      - name: 'Install Dependencies'
        run: 'sudo .github/workflows/build_and_run/install_dep.sh'

      - name: 'Build 5'
        run: '.github/workflows/build_and_run/build_5.sh'

      - name: 'Run 5'
        run: '.github/workflows/build_and_run/run_5.sh'
